name: Deploy Upload To Blockchain

on:
  push:
    branches: ["deploy"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Tag
        run: echo "tag=$(date +%s)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build, Tag & Push
        run: |
          docker build --no-cache -t upload .
          docker tag upload "nftitem/upload:$tag"
          docker tag upload "nftitem/upload:latest"
          docker push "nftitem/upload:$tag"
          docker push "nftitem/upload:latest"
